# Generated by Django 5.2.8 on 2025-12-06 14:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_time', models.TimeField(default=datetime.time(10, 0), verbose_name='Время начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('category', models.CharField(choices=[('ai_ml', 'AI/ML'), ('web_dev', 'Web Dev'), ('mobile_dev', 'Mobile Dev'), ('cyberses', 'CyberSec'), ('devops', 'DevOps'), ('analytics', 'Analytics'), ('gamedev', 'GameDev'), ('hardware', 'Hardware'), ('business', 'Business'), ('design', 'Design')], default='it', max_length=20, verbose_name='Категория')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20, verbose_name='Сложность')),
                ('max_teams', models.IntegerField(default=10, verbose_name='Максимальное количество команд')),
                ('team_size_min', models.IntegerField(default=2, verbose_name='Минимальный размер команды')),
                ('team_size_max', models.IntegerField(default=4, verbose_name='Максимальный размер команды')),
                ('registered_teams', models.IntegerField(default=0, verbose_name='Количество зарегистрированных команд')),
                ('required_roles', models.JSONField(default=list, help_text='Список требуемых ролей, например: ["frontender", "backender", "designer"]', verbose_name='Требуемые роли')),
                ('partners', models.TextField(blank=True, verbose_name='Партнёры поддержки')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Крайний срок регистрации')),
            ],
            options={
                'verbose_name': 'Хакатон',
                'verbose_name_plural': 'Хакатоны',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('telegram_id', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size_min', models.IntegerField(default=2)),
                ('size_max', models.IntegerField(default=4)),
                ('is_full', models.BooleanField(default=False)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.hackathon')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('team_invite', 'Приглашение в команду'), ('join_request', 'Запрос на присоединение')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=20)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.team')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Приглашён'), ('joined', 'Присоединился'), ('declined', 'Отклонил')], default='joined', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='mini.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_telegram_user', models.BooleanField(default=False)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Отображаемое имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('skills', models.TextField(blank=True, verbose_name='Стек технологий')),
                ('experience_months', models.IntegerField(default=0, verbose_name='Опыт в месяцах')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Продолжающий'), ('experienced', 'Опытный')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('hackathons_participated', models.IntegerField(default=0, verbose_name='Количество участий в хакатонах')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='HackathonParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('active', 'Активный'), ('approved', 'Подтверждён')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник хакатона',
                'verbose_name_plural': 'Участники хакатона',
                'unique_together': {('user', 'hackathon')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'hackathon')},
        ),
    ]
