# Generated by Django 5.2.8 on 2025-12-04 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('telegram_id', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_telegram_user', models.BooleanField(default=False)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Отображаемое имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('skills', models.TextField(blank=True, verbose_name='Стек технологий')),
                ('experience_months', models.IntegerField(default=0, verbose_name='Опыт в месяцах')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Продолжающий'), ('experienced', 'Опытный')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('hackathons_participated', models.IntegerField(default=0, verbose_name='Количество участий в хакатонах')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
