# Generated by Django 5.2.8 on 2025-12-05 18:45

from django.db import migrations, models

from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
