# Generated by Django 5.2.8 on 2025-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_add_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
