# Generated by Django 5.2.8 on 2025-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_alter_logincode_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20, verbose_name='Сложность')),
                ('max_teams', models.IntegerField(default=10, verbose_name='Максимальное количество команд')),
                ('registered_teams', models.IntegerField(default=0, verbose_name='Количество зарегистрированных команд')),
                ('required_roles', models.JSONField(default=list, help_text='Список требуемых ролей, например: ["frontender", "backender", "designer"]', verbose_name='Требуемые роли')),
            ],
            options={
                'verbose_name': 'Хакатон',
                'verbose_name_plural': 'Хакатоны',
                'ordering': ['start_date'],
            },
        ),
    ]
