# Generated by Django 5.2.8 on 2025-12-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_hackathon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='category',
            field=models.CharField(choices=[('it', 'IT'), ('robotics', 'Робототехника'), ('design', 'Дизайн'), ('other', 'Другое')], default='it', max_length=20, verbose_name='Категория'),
        ),
    ]
