# Generated by Django 5.2.8 on 2025-12-05 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_hackathon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Время начала'),
        ),
    ]
